### ISSUE TITLE
Fullscreen crashes on Windows 10

### ISSUE THREAD

**Issue by Hexaae** [PhoenixInteractiveNL/emuDownloadCenter#32]
KLive ZX Spectrum emulator is unplayable in Fullscreen mode: it crashes badly opening the screen:

Firma del problema
Nome evento problema:	APPCRASH
Nome applicazione:	Klive.exe
Versione applicazione:	0.0.0.0
Timestamp applicazione:	3d7becb8
Nome modulo con errori:	Klive.exe
Versione modulo con errori:	0.0.0.0
Timestamp modulo con errori:	3d7becb8
Codice eccezione:	c0000005
Offset eccezione:	0000bf71
Versione SO:	10.0.14393.2.0.0.768.101
ID impostazioni locali:	1040
Informazioni aggiuntive 1:	24a3
Ulteriori informazioni 2:	24a379dea9ff81e8f13946d0b7f9197b
Ulteriori informazioni 3:	c16c
Ulteriori informazioni 4:	c16c77bbb1ac812d7a3830a1f7fc9a1b

Firma del problema
Nome evento problema:	APPCRASH
Nome applicazione:	Klive.exe
Versione applicazione:	0.0.0.0
Timestamp applicazione:	3d7becb8
Nome modulo con errori:	Klive.exe
Versione modulo con errori:	0.0.0.0
Timestamp modulo con errori:	3d7becb8
Codice eccezione:	c000041d
Offset eccezione:	0000bf71
Versione SO:	10.0.14393.2.0.0.768.101
ID impostazioni locali:	1040
Informazioni aggiuntive 1:	4f8c
Ulteriori informazioni 2:	4f8ccea79b7b1f248169fc169c88fcae
Ulteriori informazioni 3:	ee44
Ulteriori informazioni 4:	ee4430bc10f26aaafd974b505f169d8d

Windows 10 x64 14393.576 nvidia driver 375.95

**Comment by PhoenixInteractiveNL** [comment]
Thanks for testing!!, i will put it in the info's ;-)
