### ISSUE TITLE
No help in Windows 10

### ISSUE THREAD

**Issue by Galbi3000** [PhoenixInteractiveNL/emuDownloadCenter#41]
The help option does not work for Windows 10 because WinHlp32 is no longer supported. There needs to be a different help system put in place that will work in all versions of Windows.

**Comment by PhoenixInteractiveNL** [comment]
Hello, there is no help function for emuDownloadCenter, i assume you mean emuControlCenter? (please post this "issue" over there)... p.s. wich version are you using?, the new version does not have a HLP file anymore.... please update!

**Comment by Galbi3000** [comment]
Sorry, I was sent to the wrong project for some reason, I should have checked before submitting the issues I submitted. My bad :)
